M48
; DRILL file {KiCad 7.0.7} date Thu Sep 28 16:31:29 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-28T16:31:29-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X40.563Y-50.165
X40.563Y-123.825
X111.125Y-50.165
X111.125Y-123.825
T0
M30
